version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.4
    ports:
      - '9093:9093'
    environment:
     - KAFKA_BROKER_ID= 1
     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_ENABLE_KRAFT=no
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_OTHER:PLAINTEXT
     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://ptvfco-d105:9093
     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
     - KAFKA_CFG_NUM_PARTITIONS=32
     - KAFKA_CFG_MESSAGE_MAX_BYTES=1000000
    depends_on:
      - zookeeper